### ISSUE TITLE
Client-side exception when using with V23.2 and setShowMoreOnScrollToBottom API

### ISSUE THREAD

**Issue by johannest** [vaadin-component-factory/vcf-noscroll-grid#12]
NoScrollGrid component does not seem to work with V23.2. I tested it with, Vite, Webpack, lazy and non-lazy DataProvider and the error is always the same:

```
noscroll-grid.js?a672:196 Uncaught TypeError: grid._toggleAttribute is not a function
    at grid.showMore (noscroll-grid.js?a672:196:1)
    at Debouncer.eval [as _callback] (noscroll-grid.js?a672:37:1)
    at eval (debounce.js?9529:39:1)
```

If I do not call `grid.setHeightFull();` the error still happens, but at least the Grid is visible. But, when calling setHeightFull, the Grid is not visible.

Vaadin version: 23.2.3
Java: 17
Windows 11 Pro

**Comment by johannest** [comment]
Looks like the issue is this call `grid.setShowMoreOnScrollToBottom(getElement());` without it, it works with V23.2.
